redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/Users/alexandrecela/Documents/CascadeProjects/windsurf-project/tiktok-creator-compass/frontend/out"
publishOrigin = "config"
commandOrigin = "config"
base = "/Users/alexandrecela/Documents/CascadeProjects/windsurf-project/tiktok-creator-compass/frontend"
command = "npm install && npm run build"

[build.environment]
NODE_VERSION = "18"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]