"""Create initial tables

Revision ID: 1cc8418b115e
Revises: 
Create Date: 2025-09-06 23:14:41.588207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cc8418b115e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('google_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('tiktok_username', sa.String(), nullable=True),
    sa.Column('offer_description', sa.Text(), nullable=True),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('weekly_updates_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_tiktok_username'), 'users', ['tiktok_username'], unique=True)
    op.create_table('creator_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recommended_username', sa.String(), nullable=False),
    sa.Column('recommended_display_name', sa.String(), nullable=True),
    sa.Column('recommended_avatar_url', sa.String(), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.Column('growth_score', sa.Float(), nullable=True),
    sa.Column('success_factors', sa.String(), nullable=True),
    sa.Column('content_themes', sa.String(), nullable=True),
    sa.Column('posting_frequency', sa.String(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creator_recommendations_id'), 'creator_recommendations', ['id'], unique=False)
    op.create_table('tiktok_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tiktok_username', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('follower_count', sa.BigInteger(), nullable=True),
    sa.Column('following_count', sa.BigInteger(), nullable=True),
    sa.Column('likes_count', sa.BigInteger(), nullable=True),
    sa.Column('video_count', sa.Integer(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tiktok_profiles_id'), 'tiktok_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_tiktok_profiles_tiktok_username'), 'tiktok_profiles', ['tiktok_username'], unique=True)
    op.create_table('profile_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('follower_growth', sa.Integer(), nullable=True),
    sa.Column('following_growth', sa.Integer(), nullable=True),
    sa.Column('video_count_growth', sa.Integer(), nullable=True),
    sa.Column('avg_views', sa.Float(), nullable=True),
    sa.Column('avg_likes', sa.Float(), nullable=True),
    sa.Column('avg_comments', sa.Float(), nullable=True),
    sa.Column('avg_shares', sa.Float(), nullable=True),
    sa.Column('avg_engagement_rate', sa.Float(), nullable=True),
    sa.Column('total_views_period', sa.Integer(), nullable=True),
    sa.Column('total_likes_period', sa.Integer(), nullable=True),
    sa.Column('reach_estimate', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['tiktok_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_analytics_id'), 'profile_analytics', ['id'], unique=False)
    op.create_table('tiktok_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('video_url', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hashtags', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.BigInteger(), nullable=True),
    sa.Column('like_count', sa.BigInteger(), nullable=True),
    sa.Column('comment_count', sa.BigInteger(), nullable=True),
    sa.Column('share_count', sa.BigInteger(), nullable=True),
    sa.Column('engagement_rate', sa.Float(), nullable=True),
    sa.Column('completion_rate', sa.Float(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['tiktok_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tiktok_videos_id'), 'tiktok_videos', ['id'], unique=False)
    op.create_index(op.f('ix_tiktok_videos_video_id'), 'tiktok_videos', ['video_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tiktok_videos_video_id'), table_name='tiktok_videos')
    op.drop_index(op.f('ix_tiktok_videos_id'), table_name='tiktok_videos')
    op.drop_table('tiktok_videos')
    op.drop_index(op.f('ix_profile_analytics_id'), table_name='profile_analytics')
    op.drop_table('profile_analytics')
    op.drop_index(op.f('ix_tiktok_profiles_tiktok_username'), table_name='tiktok_profiles')
    op.drop_index(op.f('ix_tiktok_profiles_id'), table_name='tiktok_profiles')
    op.drop_table('tiktok_profiles')
    op.drop_index(op.f('ix_creator_recommendations_id'), table_name='creator_recommendations')
    op.drop_table('creator_recommendations')
    op.drop_index(op.f('ix_users_tiktok_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
