"""Remove google_id from users

Revision ID: 2cc8418b115f
Revises: 1cc8418b115e
Create Date: 2025-09-18 23:18:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cc8418b115f'
down_revision = '1cc8418b115e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the google_id index first
    op.drop_index('ix_users_google_id', table_name='users')
    
    # Drop the google_id column
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the google_id column back
    op.add_column('users', sa.Column('google_id', sa.String(), nullable=True))
    
    # Recreate the index
    op.create_index('ix_users_google_id', 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###
